CREATE TABLE public.waybills_internal (
    waybill_id text DEFAULT nextval('public.waybills_waybill_id_seq'::regclass) NOT NULL,
    audited_date timestamp(6) with time zone,
    bag_master character varying(150),
    challan_no bigint,
    conductor_name character varying(255),
    conductor_token_no character varying(100),
    created_at timestamp(6) with time zone DEFAULT now(),
    dc_name character varying(255),
    dc_token_no character varying(100),
    deleted boolean DEFAULT false NOT NULL,
    driver_name character varying(255),
    driver_token_no character varying(100),
    duty_date character varying(20),
    device_serial_number character varying(150),
    is_flexi boolean DEFAULT false NOT NULL,
    no_of_device integer NOT NULL,
    schedule_id text NOT NULL,
    schedule_no character varying(200),
    schedule_trip_name character varying(255),
    schedule_type character varying(200),
    service_type character varying(150),
    schedule_start_time character varying(20),
    status character varying(50) DEFAULT 'active'::character varying,
    updated_at timestamp(6) with time zone DEFAULT now(),
    vehicle_no character varying(20),
    waybill_no character varying(100),
    entity_id text DEFAULT nextval('public.waybills_entity_id_seq'::regclass) NOT NULL,
    schedule_trip_id text DEFAULT nextval('public.waybills_schedule_trip_id_seq'::regclass) NOT NULL,
    service_type_id text DEFAULT nextval('public.waybills_service_type_id_seq'::regclass) NOT NULL,
    shift_type_id text DEFAULT nextval('public.waybills_shift_type_id_seq'::regclass) NOT NULL,
    tablet_id character varying(150),
    gtfs_id character varying(100) DEFAULT 'chennai_bus'::character varying NOT NULL
);
