CREATE TABLE public.stop_internal (
    bus_stop_id text DEFAULT nextval('public.bus_stop_bus_stop_id_seq'::regclass) NOT NULL,
    bus_stop_code character varying(255),
    bus_stop_name character varying(255),
    bus_stop_name_local_lang character varying(255),
    created_at timestamp(6) with time zone DEFAULT now(),
    deleted boolean DEFAULT false NOT NULL,
    description character varying(255),
    fare_stage character varying(5) DEFAULT 'N'::character varying,
    landmark character varying(255),
    latitude_current double precision NOT NULL,
    longitude_current double precision NOT NULL,
    route_status text DEFAULT 'active'::character varying,
    status character varying(255) DEFAULT 'active'::character varying,
    stop_direction character varying(255),
    stop_group_id text DEFAULT 0,
    stop_type_id text DEFAULT 0 NOT NULL,
    sub_stage character varying(5) DEFAULT 'N'::character varying,
    toll_fee integer DEFAULT 0,
    toll_zone text DEFAULT 'N'::character varying,
    updated_at timestamp(6) with time zone DEFAULT now(),
    gtfs_id character varying(100) DEFAULT 'chennai_bus'::character varying NOT NULL,
    source text
);
