CREATE TABLE public.employees (
    emp_id bigint NOT NULL,
    address character varying(255),
    basic_amount real,
    created_at timestamp(6) without time zone,
    da_amount real,
    dob date,
    deleted boolean DEFAULT false NOT NULL,
    driving_license_expiry character varying(255),
    driving_license_number character varying(255),
    email character varying(255),
    father_name character varying(255),
    first_name character varying(255) NOT NULL,
    gender character varying(50),
    last_name character varying(255),
    mobile_no character varying(15),
    status character varying(255),
    token_no character varying(50),
    updated_at timestamp(6) without time zone,
    week_off character varying(20),
    department_id bigint NOT NULL,
    designation_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    last_duty_date date,
    last_duty_shift_code character varying(255),
    last_slip_wage_date date,
    payroll_type character varying(255)
);
