CREATE TABLE public.bus_schedule_trip_flexi_internal (
    schedule_trip_flexi_id text DEFAULT nextval('public.bus_schedule_trip_flexi_schedule_trip_flexi_id_seq'::regclass) NOT NULL,
    break_time character varying(10),
    break_type character varying(255),
    created_at timestamp(6) with time zone DEFAULT now(),
    deleted boolean DEFAULT false NOT NULL,
    distance real NOT NULL,
    end_time character varying(10),
    org_name character varying(100),
    running_time character varying(10),
    schedule_number character varying(255),
    shift_day_name character varying(100),
    shift_type_name character varying(100),
    start_time character varying(10),
    trip_number integer NOT NULL,
    trip_order integer NOT NULL,
    trip_type character varying(100),
    updated_at timestamp(6) with time zone DEFAULT now(),
    calendar_id text DEFAULT nextval('public.bus_schedule_trip_flexi_calendar_id_seq'::regclass) NOT NULL,
    route_number_id text DEFAULT nextval('public.bus_schedule_trip_flexi_route_number_id_seq'::regclass) NOT NULL,
    schedule_trip_id text DEFAULT nextval('public.bus_schedule_trip_flexi_schedule_trip_id_seq'::regclass) NOT NULL,
    waybill_id text DEFAULT nextval('public.bus_schedule_trip_flexi_waybill_id_seq'::regclass) NOT NULL,
    is_active_trip boolean DEFAULT false NOT NULL,
    trip_end_time bigint,
    trip_start_time bigint,
    sync_end_time bigint,
    sync_start_time bigint,
    gtfs_id character varying(100) DEFAULT 'chennai_bus'::character varying NOT NULL
);
