CREATE TABLE public.waybills (
    waybill_id bigint NOT NULL,
    audited_date timestamp(6) without time zone,
    bag_master character varying(150),
    challan_no bigint,
    conductor_name character varying(255),
    conductor_token_no character varying(100),
    created_at timestamp(6) without time zone,
    dc_name character varying(255),
    dc_token_no character varying(100),
    deleted boolean DEFAULT false NOT NULL,
    driver_name character varying(255),
    driver_token_no character varying(100),
    duty_date character varying(20),
    device_serial_number character varying(150),
    is_flexi boolean DEFAULT false NOT NULL,
    no_of_device integer NOT NULL,
    schedule_id bigint NOT NULL,
    schedule_no character varying(200),
    schedule_trip_name character varying(255),
    schedule_type character varying(200),
    service_type character varying(150),
    schedule_start_time character varying(20),
    status character varying(50),
    updated_at timestamp(6) without time zone,
    vehicle_no character varying(20),
    waybill_no character varying(100),
    entity_id bigint NOT NULL,
    schedule_trip_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    shift_type_id bigint NOT NULL,
    audited_user_id bigint,
    is_reaudited boolean DEFAULT false NOT NULL,
    is_three_code_audited boolean DEFAULT false NOT NULL
);
