CREATE TABLE public.employees_internal (
    emp_id text DEFAULT nextval('public.employees_emp_id_seq'::regclass) NOT NULL,
    address character varying(255),
    basic_amount real,
    created_at timestamp(6) with time zone DEFAULT now(),
    da_amount real,
    dob date,
    deleted boolean DEFAULT false NOT NULL,
    driving_license_expiry character varying(255),
    driving_license_number character varying(255),
    email character varying(255),
    father_name character varying(255),
    first_name character varying(255) NOT NULL,
    gender character varying(50),
    last_name character varying(255),
    mobile_no character varying(15),
    status character varying(255) DEFAULT 'active'::character varying,
    token_no character varying(50),
    updated_at timestamp(6) with time zone DEFAULT now(),
    week_off character varying(20),
    department_id text DEFAULT nextval('public.employees_department_id_seq'::regclass) NOT NULL,
    designation_id text DEFAULT nextval('public.employees_designation_id_seq'::regclass) NOT NULL,
    entity_id text DEFAULT nextval('public.employees_entity_id_seq'::regclass) NOT NULL,
    organization_id text DEFAULT nextval('public.employees_organization_id_seq'::regclass) NOT NULL,
    gtfs_id character varying(100) DEFAULT 'chennai_bus'::character varying NOT NULL,
    email_hash character varying(255),
    password_hash character varying(255)
);
