CREATE TABLE public.bus_schedule_trip_detail (
    schedule_trip_detail_id bigint NOT NULL,
    break_time character varying(10),
    break_type character varying(255),
    created_at timestamp(6) without time zone,
    deleted boolean DEFAULT false NOT NULL,
    distance real NOT NULL,
    end_time character varying(10),
    org_name character varying(100),
    running_time character varying(10),
    schedule_number character varying(255),
    shift_day_name character varying(100),
    shift_type_name character varying(100),
    start_time character varying(10),
    trip_number integer NOT NULL,
    trip_order integer NOT NULL,
    trip_type character varying(100),
    updated_at timestamp(6) without time zone,
    calendar_id bigint NOT NULL,
    route_number_id bigint NOT NULL,
    schedule_trip_id bigint NOT NULL,
    is_active_trip boolean DEFAULT false NOT NULL,
    trip_end_time character varying(50),
    trip_start_time character varying(50),
    sync_end_time character varying(50),
    sync_start_time character varying(50)
);
