CREATE TABLE public.duties (
    id                              TEXT NOT NULL,
    duty_group_id                   TEXT NOT NULL,
    trip_id                         TEXT NOT NULL,
    gtfs_id                         TEXT NOT NULL,
    operator_id                     TEXT,
    route_id                        TEXT NOT NULL,
    is_bookable                     BOOLEAN NOT NULL,
    trip_number                     INTEGER NOT NULL,
    trip_order                      INTEGER NOT NULL,
    scheduled_start_at              TIMESTAMPTZ NOT NULL,
    scheduled_end_at                TIMESTAMPTZ NOT NULL,
    driver_token_number             TEXT,
    driver_name                     TEXT,
    conductor_token_number          TEXT,
    conductor_name                  TEXT,
    recorded_start_time             TIMESTAMPTZ,
    recorded_end_time               TIMESTAMPTZ,
    recorded_vehicle_number         TEXT,
    recorded_service_type_id        TEXT,
    run_active                      BOOLEAN NOT NULL DEFAULT true,
    status                          TEXT NOT NULL DEFAULT 'upcoming',
    cancel_reason                   TEXT,
    skip_reason                     TEXT,
    status_changed_by               TEXT,
    status_changed_at               TIMESTAMPTZ,
    deleted                         BOOLEAN NOT NULL DEFAULT false,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now()
);
