use utoipa::OpenApi;

use crate::handlers::routes;
use crate::models;
use crate::services::fleet_operator::{
    EmployeeLoginRequest, EmployeeLoginResponse, EmployeeRegisterRequest, EmployeeRegisterResponse,
};
use crate::services::operator::QueryBody;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "GTFS In-Memory Server",
        description = "GTFS Routes & Vehicle Service API",
        version = "0.1.0"
    ),
    paths(
        // Public Routes & Stops
        routes::get_routes,
        routes::get_route,
        routes::get_stops,
        routes::get_stop,
        routes::get_routes_fuzzy,
        routes::get_stops_fuzzy,
        routes::get_route_stop_mapping_by_route,
        routes::get_route_stop_mapping_draw,
        routes::get_route_stop_mapping_by_stop,
        routes::get_stop_code_from_provider_stop_code,
        routes::get_station_children,
        routes::get_alternate_stops,
        routes::get_routes_served_today,
        // Vehicle
        routes::get_service_type_by_vehicle,
        routes::get_service_type_by_vehicle_by_gtfs_id,
        routes::get_vehicle_metadata_by_gtfs_id,
        routes::get_vehicle_info,
        routes::get_vehicle_operation_data,
        routes::get_vehicle_data_eta,
        routes::get_vehicles_by_service_tier,
        routes::get_vehicles_by_depot_query,
        routes::get_conductor_by_phone_number,
        routes::get_manager_by_phone_number,
        routes::get_depot_names,
        routes::get_depot_ids,
        routes::get_depot_name_by_id,
        // Bus Schedule
        routes::get_bus_route_schedule,
        routes::get_bus_trip_schedule,
        // Bulk
        routes::get_all_routes_by_ids,
        routes::get_all_stops_by_ids,
        routes::get_all_route_stop_mappings_by_route_codes,
        routes::get_all_route_stop_mappings_by_stop_codes,
        routes::get_cluster_destinations,
        routes::get_routes_between_stops,
        routes::get_all_vehicles_by_ids,
        routes::get_routes_by_ids,
        // Trip
        routes::get_trip_data,
        routes::get_example_trip,
        routes::get_example_trip_map,
        // System
        routes::readiness_probe,
        routes::get_memory_stats,
        routes::get_version,
        routes::get_all_cached_data,
        routes::graphql_query,
        routes::get_connection_stats,
        routes::get_trip_cache_stats,
        routes::clear_trip_cache,
        routes::force_refresh_data,
        routes::clear_depot_cache,
        routes::get_cache_data_by_gtfs_id,
        // Internal Operator
        routes::get_one_row,
        routes::get_all_rows,
        routes::query_rows_handler,
        routes::delete_one_row,
        routes::upsert_one_row,
        routes::get_service_types,
        routes::get_operator_routes,
        routes::get_depots,
        routes::get_shift_types,
        routes::get_schedule_numbers,
        routes::get_day_types,
        routes::get_trip_types,
        routes::get_break_types_handler,
        routes::get_trip_details,
        routes::get_fleets,
        routes::get_conductor_data,
        routes::get_driver_info,
        routes::get_device_ids,
        routes::get_tablet_ids,
        routes::get_operators,
        routes::update_waybill_status,
        routes::update_waybill_status_v2,
        routes::update_waybill_fleet,
        routes::update_waybill_details,
        routes::update_waybill_tablet,
        routes::get_waybills,
        routes::upsert_station_eta,
        // Internal Fleet Operator
        routes::fleet_operator_current_operation,
        routes::fleet_operator_trip_action,
        routes::fleet_operator_current_trip_details,
        routes::fleet_operator_verify,
        routes::fleet_operator_employee_login,
        routes::fleet_operator_employee_register,
        routes::get_waybill_metadata,
    ),
    components(schemas(
        models::NandiRoutesRes,
        models::LatLong,
        models::GTFSStop,
        models::RouteStopMapping,
        models::ClusterRouteConnection,
        models::Gate,
        models::Stop,
        models::ServiceTierType,
        models::VehicleServiceTypeResponse,
        models::VehicleMetadataResponse,
        models::WaybillStatus,
        models::VehicleData,
        models::BusSchedule,
        models::BusScheduleDetail,
        models::BusStopETA,
        models::StopCodeFromProviderStopCodeResponse,
        models::MemoryUsageStats,
        models::TripDetails,
        models::TripStopDetail,
        models::VehicleOperationData,
        models::NandiStop,
        models::NandiTrip,
        models::NandiPattern,
        models::NandiPatternDetails,
        models::MinimalEmployee,
        routes::GetAllRoutesByIdsRequest,
        routes::GetAllStopsByIdsRequest,
        routes::GetAllRouteStopMappingsByRouteCodesRequest,
        routes::GetAllRouteStopMappingsByStopCodesRequest,
        routes::GetAllVehiclesByIdsRequest,
        routes::StationEtaUpsertRequest,
        routes::GraphQLRequest,
        routes::UpdateWaybillStatusBody,
        routes::UpdateWaybillFleetBody,
        routes::UpdateWaybillTabletBody,
        models::WaybillMetadataResponse,
        models::UpdateWaybillDetailsBody,
        routes::FleetAnchorRequest,
        routes::FleetTripActionRequest,
        routes::FleetCurrentTripDetailsRequest,
        routes::FleetVerifyRequest,
        EmployeeLoginRequest,
        EmployeeLoginResponse,
        EmployeeRegisterRequest,
        EmployeeRegisterResponse,
        crate::services::fleet_operator::AuthType,
        crate::services::fleet_operator::Role,
        QueryBody,
    )),
    tags(
        (name = "Routes", description = "Route information endpoints"),
        (name = "Stops", description = "Stop information endpoints"),
        (name = "Vehicle", description = "Vehicle and service type endpoints"),
        (name = "Schedule", description = "Bus schedule endpoints"),
        (name = "Bulk", description = "Bulk data retrieval endpoints"),
        (name = "Cluster", description = "H3 cluster-based stop endpoints"),
        (name = "Trip", description = "Trip information endpoints"),
        (name = "System", description = "Health and system info endpoints"),
        (name = "Internal Operator", description = "Internal operator CRUD and management endpoints"),
        (name = "Internal Fleet Operator", description = "Internal fleet operator endpoints"),
        (name = "Waybill", description = "Waybill metadata endpoints"),
    )
)]
pub struct ApiDoc;
